# -*- python -*-
Import('env')

pdf = [
    env.beamer('lesson1.tex'),
    env.beamer('lesson2.tex'),
    env.beamer('lesson3.tex'),
    env.beamer('lesson4.tex'),
    env.beamer('lesson5.tex'),
    env.beamer('lesson6.tex'),
]
env.Default(pdf)
